param(
    [string]$InFile,
    [string]$OutFile
)

$src = Get-Content -Raw $InFile

# Map DICTID_<NAME> = 0x......
$ids = @{}
foreach ($m in [regex]::Matches($src, 'DICTID_([A-Za-z0-9_]+)\s*=\s*(0x[0-9a-fA-F]+)')) {
    $ids[$m.Groups[1].Value] = $m.Groups[2].Value
}

# Extract each: dict_<NAME> = new byte[] { ... };
$rx = [regex]'(?s)dict_([A-Za-z0-9_]+)\s*=\s*new byte\[\]\s*\{(.*?)\}\s*;'

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// SPDX-License-Identifier: LGPL-3.0-or-later")
[void]$sb.AppendLine("// Copyright (C) 2026 s7commplus-rs contributors")
[void]$sb.AppendLine("// Ported from thomas-v2/S7CommPlusDriver Core/BlobDecompressor.cs, LGPL-3.0-or-later.")
[void]$sb.AppendLine("//")
[void]$sb.AppendLine("// @generated by tools/gen_dicts.ps1 from BlobDecompressor.cs -- DO NOT EDIT BY HAND.")
[void]$sb.AppendLine("// Regenerate: download upstream Core/BlobDecompressor.cs, then run")
[void]$sb.AppendLine("//   pwsh tools/gen_dicts.ps1 -InFile BlobDecompressor.cs -OutFile src/optimized/dict.rs")
[void]$sb.AppendLine("// The 19 zlib preset dictionaries used to inflate S7CommPlus type-metadata blobs.")
[void]$sb.AppendLine("// Each is selected at inflate time by matching the Adler-32 the stream reports as")
[void]$sb.AppendLine("// its required dictionary id (the zlib Z_NEED_DICT flow).")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("/// A zlib preset dictionary keyed by its Adler-32 dictionary id.")
[void]$sb.AppendLine("pub(crate) struct PresetDict {")
[void]$sb.AppendLine("    pub adler: u32,")
[void]$sb.AppendLine("    pub name: &'static str,")
[void]$sb.AppendLine("    pub bytes: &'static [u8],")
[void]$sb.AppendLine("}")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("pub(crate) static PRESET_DICTIONARIES: &[PresetDict] = &[")

$count = 0
foreach ($m in $rx.Matches($src)) {
    $name = $m.Groups[1].Value
    $body = $m.Groups[2].Value
    if (-not $ids.ContainsKey($name)) {
        Write-Error "no DICTID for dict_$name"
        exit 1
    }
    $adler = $ids[$name]
    $bytes = [regex]::Matches($body, '0x[0-9a-fA-F]+') | ForEach-Object { $_.Value }
    $count++
    [void]$sb.AppendLine("    PresetDict {")
    [void]$sb.AppendLine("        adler: $adler,")
    [void]$sb.AppendLine("        name: `"$name`",")
    [void]$sb.Append("        bytes: &[")
    for ($i = 0; $i -lt $bytes.Count; $i++) {
        if ($i % 16 -eq 0) { [void]$sb.Append("`r`n            ") }
        [void]$sb.Append($bytes[$i])
        [void]$sb.Append(", ")
    }
    [void]$sb.AppendLine("`r`n        ],")
    [void]$sb.AppendLine("    },")
}

[void]$sb.AppendLine("];")

Set-Content -Path $OutFile -Value $sb.ToString() -Encoding utf8
Write-Output "wrote $count dictionaries to $OutFile"
